import { useRef, useState } from 'react';
import { Bell, Bookmark, CalendarCheck, ChevronRight, Coins, Crown, History, LockKeyhole, MessageCircle, Settings, UserRound, LogOut } from 'lucide-react';
import { dramas, type Drama } from '../data/dramas';
import { useApp, readLocal } from '../state/appState';
const avatarFor = (subject?: string | null) => subject ? readLocal<string>('aiai-avatar:' + subject, '') : '';
import { api, dateText, enc, messageOf, type Notice, type Profile, type Progress, type Comment } from '../services/api';
import { useResource } from '../hooks/useResource';
import { DramaRows, Empty, ErrorState, PageShell } from './Common';
type Navigate = (to: string) => void;
export function ProfileScreen({ navigate, onOpen }: { navigate: Navigate; onOpen: (d: Drama) => void }) {
  const { session, checking, records, login } = useApp();
  const recent = records.history.map(p => dramas.find(d => d.id === p.contentId)).filter((d): d is Drama => !!d).slice(0, 3);
  return <main className="profile-screen"><header className="profile-head"><div className="avatar">{avatarFor(session?.subject) ? <img src={avatarFor(session?.subject)} alt="个人头像"/> : <UserRound size={28}/>}</div><div><strong>{session?.nickname || (session?.subject ? '爱爱短剧用户' : '登录爱爱短剧')}</strong><span>{checking ? '正在检查登录状态…' : session?.subject ? '好故事，一起追' : '登录后管理账户与评论'}</span></div><button onClick={() => session?.subject ? navigate('/me/profile') : login()}>{session?.subject ? '编辑' : '登录'}</button></header>
    <button className="profile-member" onClick={() => navigate('/membership')}><span><small><Crown size={14}/>会员中心</small><strong>{session?.tier && session.tier !== 'free' ? '畅看会员' : '免费用户 · 可领取24小时体验'}</strong><i>{session?.membership?.expiresAt ? `有效期至 ${new Date(session.membership.expiresAt).toLocaleDateString('zh-CN')}` : '查看权益与会员方案'}</i></span><ChevronRight size={20}/></button>
    <button className="daily-checkin-entry" onClick={() => navigate('/me/points')}><CalendarCheck/><span><strong>每日签到</strong><small>查看永久积分、会员积分与七日奖励</small></span><ChevronRight/></button>
    <section className="profile-shortcuts">{[{ icon: Coins, title: '积分', path: '/me/points' }, { icon: History, title: '观看历史', path: '/me/history' }, { icon: Bookmark, title: '我的追剧', path: '/me/favorites' }, { icon: MessageCircle, title: '我的评论', path: '/me/comments' }, { icon: Bell, title: '消息中心', path: '/me/messages' }].map(({ icon: Icon, title, path }) => <button key={path} onClick={() => navigate(path)}><span><Icon size={21}/></span><small>{title}</small></button>)}</section>
    <section className="profile-section"><div className="section-heading"><h2>最近观看</h2><button className="text-button" onClick={() => navigate('/me/history')}>全部<ChevronRight size={15}/></button></div>{recent.length ? <DramaRows items={recent} onOpen={onOpen}/> : <div className="mini-empty">还没有观看记录，去发现喜欢的故事吧。</div>}</section>
    <section className="settings-list">{[['24小时体验与会员中心', '/membership'], ['我的订单', '/me/orders'], ['个人资料与修改密码', '/me/profile'], ['隐私设置', '/me/privacy'], ['帮助与反馈', '/support'], ['私密空间', '/18plus'], ['关于爱爱短剧', '/about']].map(([title, path]) => <button key={path} onClick={() => navigate(path)}><span>{title}</span>{path === '/18plus' ? <LockKeyhole size={18}/> : <ChevronRight size={18}/>}</button>)}</section>
    <LogoutButton/>
  </main>;
}
function LogoutButton() {
  const { session, accept } = useApp();
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  const lock = useRef(false);
  if (!session?.subject) return null;
  return <div className="profile-logout">{error && <p role="alert">{error}</p>}<button className="secondary-button" disabled={busy} onClick={async () => {
    if (lock.current) return;
    lock.current = true; setBusy(true); setError('');
    try { await api('/session', 'DELETE'); accept(null); }
    catch (e) { setError(messageOf(e)); }
    finally { lock.current = false; setBusy(false); }
  }}><LogOut size={18}/>{busy ? '正在退出…' : '退出账号'}</button></div>;
}

export function LibraryScreen({ onOpen, navigate }: { onOpen: (d: Drama) => void; navigate: Navigate; tab?: 'following' | 'saved' }) {
  const { records } = useApp(), [query, setQuery] = useState('');
  const items = dramas.filter(d => records.following.includes(d.id) && d.title.includes(query.trim()));
  return <main className="library-screen"><header className="page-header"><div><small>“追剧”和原“收藏”已合并为同一份数据</small><h1>我的追剧</h1></div><Bookmark/></header><label className="search-field"><input aria-label="搜索我的追剧" placeholder="搜索我的追剧" value={query} onChange={e => setQuery(e.target.value)}/></label>{items.length ? <DramaRows items={items} onOpen={onOpen}/> : <Empty title={query ? '没有匹配的剧目' : '追剧列表还是空的'} text="在作品详情、播放页或刷剧页加入追剧后会显示在这里。"><button className="primary-button" onClick={() => navigate('/')}>去发现好剧</button></Empty>}</main>;
}
function LoginRequired() { const { login } = useApp(); return <Empty title="请先登录" text="登录后查看并管理账号内容。"><button className="primary-button" onClick={login}>登录 / 注册</button></Empty>; }
export function AccountPage({ kind, onBack, navigate, onOpen }: { kind: string; onBack: () => void; navigate: Navigate; onOpen: (d: Drama) => void }) {
  const title: Record<string, string> = { profile: '个人资料', history: '观看记录', favorites: '我的追剧', comments: '我的评论', messages: '消息中心', privacy: '隐私设置' };
  const { session } = useApp();
  return <PageShell title={title[kind] || '个人中心'} onBack={onBack}>{kind === 'history' ? <HistoryContent onOpen={onOpen}/> : kind === 'favorites' ? <LibraryScreen onOpen={onOpen} navigate={navigate}/> : kind === 'privacy' ? <SettingsContent navigate={navigate}/> : !session?.subject ? <LoginRequired/> : kind === 'profile' ? <ProfileContent navigate={navigate}/> : kind === 'messages' ? <MessagesContent navigate={navigate}/> : <MyCommentsContent onOpen={onOpen}/>}</PageShell>;
}
function ProfileContent({ navigate }: { navigate: Navigate }) {
  const { session, accept } = useApp(), resource = useResource<Profile>('/me/profile');
  const [avatar, setAvatar] = useState(() => avatarFor(session?.subject)), [avatarError, setAvatarError] = useState('');
  const [nickname, setNickname] = useState<string | null>(null), [bio, setBio] = useState<string | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  if (resource.loading) return <p role="status" className="muted">正在加载资料…</p>;
  if (resource.error) return <ErrorState error={resource.error} retry={resource.reload}/>;
  return <form className="form-stack" onSubmit={async e => { e.preventDefault(); if (busy) return; setBusy(true); setMessage(''); try { const p = await api<Profile>('/me/profile', 'PATCH', { nickname: (nickname ?? resource.data?.nickname ?? '').trim(), bio: (bio ?? resource.data?.bio ?? '').trim() }); resource.setData(p); if (session) accept({ ...session, nickname: p.nickname }); setMessage('资料已保存'); } catch (e) { setMessage(messageOf(e)); } finally { setBusy(false); } }}><div className="profile-avatar-large">{avatar || resource.data?.avatarUrl ? <img src={avatar || resource.data?.avatarUrl || ''} alt="个人头像"/> : <UserRound size={38}/>}</div><label>更换头像<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => { const element = e.currentTarget, file = element.files?.[0]; if (!file || !session?.subject) return; setAvatarError(''); if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 2 * 1024 * 1024) { setAvatarError('请选择不超过 2 MB 的 JPG、PNG 或 WebP 图片。'); element.value = ''; return; } const subject = session.subject; const reader = new FileReader(); reader.onload = () => { const value = String(reader.result); const image = new Image(); image.onload = () => { try { localStorage.setItem('aiai-avatar:' + subject, JSON.stringify(value)); setAvatar(value); } catch { setAvatarError('设备存储空间不足，请使用更小的图片。'); } }; image.onerror = () => setAvatarError('图片无法读取，请换一张图片。'); image.src = value; element.value = ''; }; reader.onerror = () => setAvatarError('图片读取失败，请重试。'); reader.readAsDataURL(file); }}/><small className="muted">头像保存在当前设备，支持 JPG、PNG、WebP。</small></label>{avatarError && <ErrorState error={avatarError}/>}<button type="button" className="text-button" onClick={() => { try { localStorage.removeItem('aiai-avatar:' + session?.subject); setAvatar(''); setAvatarError(''); } catch { setAvatarError('暂时无法清除头像，请重试。'); } }}>恢复默认头像</button><label>登录账号<input disabled value={session?.subject ?? ''}/></label><label>昵称<input minLength={2} maxLength={24} required value={nickname ?? resource.data?.nickname ?? ''} onChange={e => setNickname(e.target.value)}/></label><label>个人简介<textarea maxLength={120} value={bio ?? resource.data?.bio ?? ''} onChange={e => setBio(e.target.value)} placeholder="介绍一下自己吧"/></label>{message && <p role="status">{message}</p>}<button className="primary-button" disabled={busy}>{busy ? '保存中…' : '保存资料'}</button><button type="button" className="secondary-button" onClick={() => navigate('/account/forgot-password')}>修改 / 找回密码</button></form>;
}
function HistoryContent({ onOpen }: { onOpen: (d: Drama) => void }) {
  const { records, clearHistory, session } = useApp(), remote = useResource<Progress[]>(session?.subject ? '/me/watch-progress' : null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const merged = [...records.history, ...(remote.data ?? [])].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).filter((p, i, arr) => arr.findIndex(v => v.contentId === p.contentId) === i);
  const remove = async (id?: string) => { setBusy(true); setError(''); try { if (session?.subject) await api('/privacy/green/history' + (id ? '/' + enc(id) : ''), 'DELETE'); clearHistory(id); remote.setData(v => id ? v?.filter(p => p.contentId !== id) ?? [] : []); } catch (e) { setError(messageOf(e)); } finally { setBusy(false); } };
  return <><p className="muted">从上次停下的位置继续。访客记录保存在当前设备。</p>{remote.error && <ErrorState error={remote.error} retry={remote.reload}/>}<div className="history-list">{merged.map(p => { const item = dramas.find(d => d.id === p.contentId); return item ? <article key={p.contentId}><button onClick={() => onOpen(item)}><img src={item.cover} alt=""/><span><strong>{item.title}</strong><small>第 {p.episodeId} 集 · 已看 {Math.round(p.seconds)} 秒</small><small>{dateText(p.updatedAt)}</small></span></button><button disabled={busy} aria-label={'删除记录 ' + item.title} onClick={() => void remove(item.id)}>删除</button></article> : null; })}</div>{!merged.length && <Empty title="暂无观看记录"/>}{error && <ErrorState error={error}/>}<button className="secondary-button" disabled={busy || !merged.length} onClick={() => void remove()}>清空观看记录</button></>;
}
function MessagesContent({ navigate }: { navigate: Navigate }) {
  const r = useResource<Notice[]>('/me/notifications'), [filter, setFilter] = useState('all'), [error, setError] = useState('');
  return <><div className="chip-tabs">{[['all', '全部'], ['reply', '回复'], ['update', '更新'], ['system', '系统']].map(([id, label]) => <button key={id} aria-pressed={filter === id} onClick={() => setFilter(id)}>{label}</button>)}</div>{r.loading ? <p role="status">正在加载消息…</p> : r.error ? <ErrorState error={r.error} retry={r.reload}/> : <>{(r.data ?? []).filter(n => filter === 'all' || n.kind === filter).map(n => <article className="notice-card" key={n.id}><h3>{!n.read && <i/>}{n.title}</h3><p>{n.body}</p><small>{dateText(n.createdAt)}</small><button onClick={async () => { try { await api('/me/notifications/' + enc(n.id), 'PATCH', { read: true }); r.setData(v => v?.map(i => i.id === n.id ? { ...i, read: true } : i) ?? []); if (n.href.startsWith('/') && !n.href.startsWith('//')) navigate(n.href); } catch (e) { setError(messageOf(e)); } }}>查看消息</button></article>)}{!(r.data ?? []).some(n => filter === 'all' || n.kind === filter) && <Empty title="暂无消息"/>}</>}{error && <ErrorState error={error}/>}</>;
}
function MyCommentsContent({ onOpen }: { onOpen: (d: Drama) => void }) {
  const r = useResource<Comment[]>('/me/comments'), [error, setError] = useState('');
  return <>{r.loading ? <p role="status">正在加载评论…</p> : r.error ? <ErrorState error={r.error} retry={r.reload}/> : r.data?.length ? r.data.map(c => <article className="notice-card" key={c.id}><small>{dateText(c.createdAt)} · {c.status === 'pending' ? '审核中' : c.status === 'rejected' ? '未通过' : '已发布'}</small><p>{c.content}</p><button onClick={() => { const d = dramas.find(d => d.id === c.contentId); if (d) onOpen(d); }}>查看剧目</button><button onClick={async () => { try { await api('/comments/' + enc(c.id), 'DELETE'); r.setData(v => v?.filter(i => i.id !== c.id) ?? []); } catch (e) { setError(messageOf(e)); } }}>删除</button></article>) : <Empty title="还没有评论" text="看剧时留下你的想法吧。"/>}{error && <ErrorState error={error}/>}</>;
}
function SettingsContent({ navigate }: { navigate: Navigate }) {
  const { clearRecords, records } = useApp(), [message, setMessage] = useState(''), [hideFollowing, setHideFollowing] = useState(()=>readLocal('aiai-privacy-hide-following',false)), [hidePrivate, setHidePrivate] = useState(()=>readLocal('aiai-privacy-hide-private',true)), [neutral, setNeutral] = useState(()=>readLocal('aiai-privacy-neutral-notifications',true));
  const toggleSetting=(key:string,value:boolean,setter:(v:boolean)=>void)=>{setter(value);try{localStorage.setItem(key,JSON.stringify(value));}catch{setMessage('设备设置保存失败，请检查浏览器存储权限。');}};
  return <><div className="settings-intro"><Settings size={26}/><h2>隐私与设备记录</h2><p>普通区追剧、点赞与访客观看记录保存在当前设备；登录后的云端记录属于账号数据。18+愿望榜只存在当前专区会话。</p></div><section className="privacy-options"><label><span><strong>隐藏普通区关注记录</strong><small>在当前设备界面隐藏追剧信息。</small></span><input type="checkbox" checked={hideFollowing} onChange={e=>toggleSetting('aiai-privacy-hide-following',e.target.checked,setHideFollowing)}/></label><label><span><strong>隐藏私密观看历史</strong><small>专区退出后访问资格与愿望榜会清除。</small></span><input type="checkbox" checked={hidePrivate} onChange={e=>toggleSetting('aiai-privacy-hide-private',e.target.checked,setHidePrivate)}/></label><label><span><strong>通知内容脱敏</strong><small>通知预览中隐藏作品名称。</small></span><input type="checkbox" checked={neutral} onChange={e=>toggleSetting('aiai-privacy-neutral-notifications',e.target.checked,setNeutral)}/></label></section><section className="settings-list"><button onClick={()=>{clearRecords('ordinary');setMessage('已清空当前设备普通记录。');}}>清空当前设备普通记录 <small>{records.following.length+records.history.length} 条</small></button><button onClick={()=>{clearRecords('private');setMessage('已撤销专区访问资格并清空当前会话私密记录。');}}>清空当前设备私密记录</button>{records.following.map(id=><button key={id} onClick={()=>{const item=dramas.find(d=>d.id===id); if(item) navigate('/detail/'+encodeURIComponent(item.id));}}>{dramas.find(d=>d.id===id)?.title||'已不可用内容'}<ChevronRight size={17}/></button>)}</section>{message&&<p role="status">{message}</p>}<button className="secondary-button" onClick={()=>navigate('/privacy')}>查看隐私政策</button></>;
}
