import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ChevronRight, Heart, Play, Search, ShieldCheck } from 'lucide-react';
import { AnimatePresence, motion } from 'motion/react';
import { adultBanners, adultDramas, type AdultDrama, type AdultTab } from '../data/adult';
import { useReducedMotion } from '../hooks/useReducedMotion';
import { api } from '../services/api';
import { assetUrl } from '../utils/assets';

function AdultPosterGrid({ items, saved, onSave, onOpen }: { items: AdultDrama[]; saved: string[]; onSave: (id: string) => void; onOpen: (item: AdultDrama) => void }) {
  if (!items.length) return <div className="content-empty"><strong>暂无符合条件的专区内容</strong><span>调整频道或搜索条件后再看看。</span></div>;
  return <div className="adult-grid">{items.map(item => <article className="adult-card" key={item.id}><button className="adult-cover" onClick={() => onOpen(item)} aria-label={`查看《${item.title}》`}><img src={item.cover} alt={item.title} loading="lazy"/><span className="adult-cover-shade"/>{item.original && <span className="adult-original">原创</span>}<span className="adult-status">{item.status}</span></button><div className="adult-card-copy"><button onClick={() => onOpen(item)}><strong>{item.title}</strong><small>{item.genre} · {item.channel}</small></button><button className="adult-save" aria-label={saved.includes(item.id) ? `移出愿望榜${item.title}` : `加入愿望榜${item.title}`} aria-pressed={saved.includes(item.id)} onClick={() => onSave(item.id)}><Heart size={18} fill={saved.includes(item.id) ? 'currentColor' : 'none'}/></button></div></article>)}</div>;
}
function AdultHero({ onOpen, onFestival }: { onOpen: (item: AdultDrama) => void; onFestival: () => void }) {
  const reduced = useReducedMotion(), [index, setIndex] = useState(0), [manual, setManual] = useState(false);
  const slides = [{ id: 'festival', title: '双节好礼', image: assetUrl('assets/festival/home-festival-panorama.png'), genre: '任务最高领 350 永久积分', synopsis: '月卡加赠 7 天，季卡加赠 30 天' }, ...adultBanners];
  const banner = slides[index];
  useEffect(() => { if (manual || reduced) return; const timer = window.setInterval(() => setIndex(value => (value + 1) % slides.length), 6000); return () => clearInterval(timer); }, [manual, reduced, slides.length]);
  return <section className="adult-hero" aria-label="专区轮播"><AnimatePresence mode="wait"><motion.button className="adult-hero-card" key={banner.id} onClick={() => index === 0 ? onFestival() : onOpen(adultDramas[index - 1])} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: reduced ? 0 : .3 }}><img src={banner.image} alt=""/><span className="adult-hero-shade"/><span className="adult-hero-copy"><small>{index === 0 ? '双节活动' : '专区精选'} · {banner.genre}</small><strong>{banner.title}</strong><span>{banner.synopsis || '封面预览，剧情资料待补充。'}</span><i><Play size={14} fill="currentColor"/>{index === 0 ? '查看活动' : '查看作品'}</i></span></motion.button></AnimatePresence><div className="adult-hero-dots">{slides.map((item, i) => <button className={i === index ? 'active' : ''} key={item.id} onClick={() => { setManual(true); setIndex(i); }} aria-label={`切换到${item.title}`}/>)}</div></section>;
}
export function AdultScreen({ route, onBack, onSearch, onOpen, navigate }: { route: string; onBack: () => void; onSearch: () => void; onOpen: (item: AdultDrama) => void; navigate: (path: string) => void }) {
  const [confirmed, setConfirmed] = useState(() => { try { return sessionStorage.getItem('aiai-adult-confirmed') === '1'; } catch { return false; } });
  const [age, setAge] = useState(false), [tab, setTab] = useState<AdultTab>('首页'), [wishlist, setWishlist] = useState<string[]>([]), [busy, setBusy] = useState(false), [gateError, setGateError] = useState('');
  const wishlistView = route.split('?')[0] === '/18plus/wishlist';
  useEffect(() => { const path = route.split('?')[0]; if (!path.startsWith('/18plus') && !path.startsWith('/detail/')) { try { sessionStorage.removeItem('aiai-adult-confirmed'); } catch {} setConfirmed(false); setAge(false); setWishlist([]); } }, [route]);
  const visible = useMemo(() => { if (wishlistView) return adultDramas.filter(item => wishlist.includes(item.id)); if (tab === '成人短剧') return adultDramas.filter(item => item.format === 'live_action_drama'); if (tab === '成人漫剧') return adultDramas.filter(item => item.format === 'motion_comic'); if (tab === '原创') return adultDramas.filter(item => item.original); if (tab === '最新') return [...adultDramas].reverse(); if (tab === '热门') return [...adultDramas].sort((a,b) => Number(b.original) - Number(a.original)); return adultDramas; }, [tab, wishlistView, wishlist]);
  const confirm = async () => { if (!age || busy) return; setBusy(true); setGateError(''); try { sessionStorage.setItem('aiai-adult-confirmed', '1'); } catch {} setConfirmed(true); setBusy(false); void api('/adult/consent', 'POST', { ageConfirmed: true, explicitConsent: true }).catch(() => {}); };
  const leaveZone = () => { void api('/adult/consent', 'DELETE').catch(() => {}); try { sessionStorage.removeItem('aiai-adult-confirmed'); } catch {} setConfirmed(false); setAge(false); setTab('首页'); setWishlist([]); onBack(); };
  const toggleSave = (id: string) => setWishlist(value => value.includes(id) ? value.filter(item => item !== id) : [...value, id]);
  if (!confirmed) return <main className="adult-gate"><button className="adult-gate-back" onClick={onBack}><ArrowLeft size={18}/>返回普通区</button><div className="adult-gate-mark"><ShieldCheck size={31}/></div><h1>进入18+专区</h1><p>本专区仅面向已满18周岁的用户。请确认年龄后主动进入。</p><label className="age-confirm"><input type="checkbox" checked={age} onChange={e => setAge(e.target.checked)}/>我已年满18周岁</label>{gateError && <p role="alert" className="form-error">{gateError} 请重新尝试。</p>}<button className="adult-confirm" disabled={!age || busy} onClick={() => void confirm()}>{busy ? '正在确认…' : '确认并进入'} {!busy && <ChevronRight size={17}/>}</button><button className="adult-cancel" disabled={busy} onClick={onBack}>返回普通区</button></main>;
  return <main className="adult-screen"><header className="adult-topbar"><button className="adult-icon-button" onClick={wishlistView ? () => navigate('/18plus') : onBack} aria-label="返回"><ArrowLeft size={20}/></button><div className="adult-title"><img src={assetUrl('assets/brand/logo-mark.svg')} alt=""/><span><strong>{wishlistView ? '私密愿望榜' : '18+专区'}</strong><small>仅限已满18周岁用户</small></span></div><button className="adult-icon-button" onClick={onSearch} aria-label="搜索专区内容"><Search size={20}/></button></header>{!wishlistView && <div className="adult-tabs" role="tablist" aria-label="专区频道">{(['首页', '成人短剧', '成人漫剧', '原创', '最新', '热门'] as AdultTab[]).map(name => <button role="tab" aria-selected={tab === name} key={name} onClick={() => setTab(name)}>{name}</button>)}</div>}{tab === '首页' && !wishlistView ? <><AdultHero onOpen={onOpen} onFestival={() => navigate('/festival')}/><section className="adult-section"><div className="adult-section-heading"><span><small>为你精选</small><h2>精选推荐</h2></span><button onClick={() => setTab('热门')}>更多 <ChevronRight size={15}/></button></div><AdultPosterGrid items={adultDramas.slice(0, 4)} saved={wishlist} onSave={toggleSave} onOpen={onOpen}/></section><section className="adult-section"><div className="adult-section-heading"><span><small>最近更新</small><h2>最近上新</h2></span><button onClick={() => setTab('最新')}>全部 <ChevronRight size={15}/></button></div><AdultPosterGrid items={adultDramas.slice(4, 12)} saved={wishlist} onSave={toggleSave} onOpen={onOpen}/></section><section className="adult-ad-row" aria-label="广告位">{[1,2,3].map(n => <div className="adult-ad-slot" key={n}><span>广告</span><strong>品牌合作</strong><small>ADVERTISEMENT · {String(n).padStart(2,'0')}</small></div>)}</section><button className="adult-wishlist" onClick={() => navigate('/18plus/wishlist')}><span><small>私密愿望榜</small><strong>把心动，留到下一场。</strong><i>{wishlist.length ? `本次会话已保存 ${wishlist.length} 部` : '不上传 · 不公开 · 退出即清除'}</i></span><ChevronRight size={20}/></button></> : <section className="adult-section adult-filtered"><div className="adult-section-heading"><span><small>{wishlistView ? '仅本次专区会话保存' : '专区筛选'}</small><h2>{wishlistView ? '私密愿望榜' : tab}</h2></span><em>{visible.length} 部内容</em></div><AdultPosterGrid items={visible} saved={wishlist} onSave={toggleSave} onOpen={onOpen}/></section>}<footer className="adult-footer"><strong>私密内容不提供公开分享</strong><span>愿望榜刷新、退出专区或资格失效后清除</span><button onClick={leaveZone}>退出专区</button></footer></main>;
}
