import { useEffect, useMemo, useRef, useState } from 'react';
import { Heart, MessageCircle, Send, UserRound } from 'lucide-react';
import { api, enc, messageOf, dateText, type Comment } from '../services/api';
import { useApp } from '../state/appState';
import { ErrorState } from './Common';
import { Sheet } from './Sheets';
export function Comments({ contentId, episodeId = '1', compact = false }: { contentId: string; episodeId?: string; compact?: boolean }) {
  const { session, login } = useApp();
  const key = 'aiai-draft:' + contentId + ':' + episodeId + ':' + (session?.subject ?? 'guest');
  const [items, setItems] = useState<Comment[]>([]), [cursor, setCursor] = useState<string | null>(null), [sort, setSort] = useState<'hot' | 'latest'>('hot'), [draft, setDraft] = useState(''), [spoiler, setSpoiler] = useState(false), [reply, setReply] = useState<Comment | null>(null), [report, setReport] = useState<Comment | null>(null), [reason, setReason] = useState('垃圾广告'), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(''), [loadError, setLoadError] = useState(''), [revision, setRevision] = useState(0);
  const input = useRef<HTMLTextAreaElement>(null), pending = useRef(false), submission = useRef({ text: '', id: '' });
  useEffect(() => { try { setDraft(sessionStorage.getItem(key) || sessionStorage.getItem('aiai-draft:' + contentId + ':' + episodeId + ':guest') || ''); } catch {} }, [key]);
  const changeDraft = (text: string) => { setDraft(text); try { sessionStorage.setItem(key, text); } catch {} };
  useEffect(() => { const c = new AbortController(); setLoading(true); setLoadError(''); setItems([]); setReply(null); api<{ items: Comment[]; cursor: string | null }>('/comments?contentId=' + enc(contentId) + '&episodeId=' + enc(episodeId), 'GET', undefined, c.signal).then(r => { setItems(r.items); setCursor(r.cursor); }).catch(e => { if (!c.signal.aborted) setLoadError(messageOf(e)); }).finally(() => { if (!c.signal.aborted) setLoading(false); }); return () => c.abort(); }, [contentId, episodeId, revision, session?.subject]);
  const list = useMemo(() => [...items].filter(i => !i.parentId).sort((a, b) => sort === 'hot' ? b.likeCount - a.likeCount || b.createdAt.localeCompare(a.createdAt) : b.createdAt.localeCompare(a.createdAt)), [items, sort]);
  async function perform(fn: () => Promise<void>) { if (pending.current) return; pending.current = true; setBusy(true); setError(''); try { await fn(); } catch (e) { setError(messageOf(e)); } finally { pending.current = false; setBusy(false); } }
  const publish = (e: React.FormEvent) => { e.preventDefault(); if (!session?.subject) { login(); return; } if (draft.trim().length < 2) { setError('请输入至少 2 个字。'); return; }
    void perform(async () => { const text = JSON.stringify([draft.trim(), reply?.id, spoiler]); if (submission.current.text !== text) submission.current = { text, id: crypto.randomUUID() };
      const created = await api<Comment>('/comments', 'POST', { contentId, episodeId, parentId: reply?.id, content: draft.trim(), spoiler, idempotencyKey: submission.current.id });
      setItems(v => [created, ...v.filter(i => i.id !== created.id)]); changeDraft(''); try { sessionStorage.removeItem('aiai-draft:' + contentId + ':' + episodeId + ':guest'); } catch {} setReply(null); setSpoiler(false); submission.current = { text: '', id: '' };
    });
  };
  function renderComment(item: Comment, nested = false) { return <article className={'discussion-item ' + (nested ? 'is-reply' : '')} key={item.id}><span className="discussion-avatar"><UserRound size={17}/></span><div className="discussion-body"><strong>{item.author.nickname}</strong>{item.spoiler ? <details><summary>包含剧透 · 点击查看</summary><p>{item.content}</p></details> : <p>{item.content}</p>}{item.status !== 'published' && <small>{item.status === 'pending' ? '审核中' : '审核未通过'}</small>}<div className="discussion-meta"><time>{dateText(item.createdAt)}</time><button aria-label="赞评论" aria-pressed={item.liked} disabled={busy} onClick={() => { if (!session?.subject) { login(); return; } void perform(async () => { const result = await api<{ liked: boolean; likeCount: number }>('/comments/' + enc(item.id) + '/like', item.liked ? 'DELETE' : 'PUT'); setItems(v => v.map(i => i.id === item.id ? { ...i, ...result } : i)); }); }}><Heart size={13} fill={item.liked ? 'currentColor' : 'none'}/>{item.likeCount}</button><button onClick={() => { setReply(item); input.current?.focus(); }}><MessageCircle size={13}/>回复</button></div><div className="discussion-tools">{session?.subject === item.author.id ? <button disabled={busy} onClick={() => void perform(async () => { await api('/comments/' + enc(item.id), 'DELETE'); setItems(v => v.filter(i => i.id !== item.id && i.parentId !== item.id)); })}>删除</button> : <button onClick={() => { if (!session?.subject) login(); else setReport(item); }}>举报</button>}</div>{!nested && items.filter(i => i.parentId === item.id).map(i => renderComment(i, true))}</div></article>; }
  return <section className={'discussion ' + (compact ? 'compact' : '')}><header><h2>评论{!loading && !loadError ? ' (' + items.length + ')' : ''}</h2><div className="segmented"><button aria-pressed={sort === 'hot'} onClick={() => setSort('hot')}>热门</button><button aria-pressed={sort === 'latest'} onClick={() => setSort('latest')}>最新</button></div></header>
    <form className="discussion-form" onSubmit={publish}>{reply && <div className="reply-hint">回复 {reply.author.nickname}<button type="button" onClick={() => setReply(null)}>取消</button></div>}<div className="discussion-input"><textarea ref={input} aria-label="评论内容" placeholder="说说你的看法…" maxLength={500} value={draft} onChange={e => changeDraft(e.target.value)}/><button type="submit" aria-label="发送评论" disabled={busy || loading || !draft.trim()}><Send size={20}/></button></div>{draft && <div className="composer-options"><label><input type="checkbox" checked={spoiler} onChange={e => setSpoiler(e.target.checked)}/>包含剧透</label><small>{draft.length}/500</small></div>}</form>
    {error && <ErrorState error={error}/>}
    {loading ? <p className="muted" role="status">正在加载评论…</p> : loadError ? <ErrorState error={loadError} retry={() => setRevision(v => v + 1)}/> : !list.length ? <p className="muted">还没有评论，来聊聊这部剧吧。</p> : list.map(i => renderComment(i))}
    {cursor && <button className="secondary-button" disabled={busy} onClick={() => void perform(async () => { const r = await api<{ items: Comment[]; cursor: string | null }>('/comments?contentId=' + enc(contentId) + '&episodeId=' + enc(episodeId) + '&cursor=' + enc(cursor)); setItems(v => [...v, ...r.items.filter(i => !v.some(old => old.id === i.id))]); setCursor(r.cursor); })}>加载更多评论</button>}
    <Sheet open={!!report} title="举报评论" onClose={() => setReport(null)}><div className="form-stack"><label>举报原因<select value={reason} onChange={e => setReason(e.target.value)}>{['垃圾广告', '人身攻击', '违法违规', '泄露隐私'].map(v => <option key={v}>{v}</option>)}</select></label>{error && <ErrorState error={error}/>}<button className="primary-button" disabled={busy} onClick={() => void perform(async () => { await api('/comments/' + enc(report!.id) + '/reports', 'POST', { reason }); setReport(null); setError('举报已提交，感谢反馈。'); })}>提交举报</button></div></Sheet>
  </section>;
}
