import { useEffect, useRef, useState } from 'react';
import { api, dateText, enc, messageOf, safeDecode, type Order } from '../services/api';
import { useApp } from '../state/appState';
import { useResource } from '../hooks/useResource';
import { products, festivalBonus, money } from '../data/membershipOffers';
import { festivalPhase } from '../data/festival';
import { PageShell, Empty, ErrorState } from './Common';
type Props = { route: string; navigate: (path: string) => void; onBack: () => void };
type Quote = { id: string; planId: string; total: number; currency: string; expiresAt: string; autoRenew: false; durationDays?: number|null; validity?: 'fixed'|'permanent' };
type RichOrder = Order & { productId?: string; productName?: string; durationDays?: number|null; validity?: 'fixed'|'permanent'; extraViewingDays?: number; entitlementStatus?: string; entitlementExpiresAt?: string|null; refundStatus?: string|null };
const orderStatus: Record<string, string> = { pending:'待支付',processing:'处理中',paid:'已支付',closed:'已关闭',refunding:'退款中',refunded:'已退款',cancelled:'已取消',failed:'支付失败' };
function Checkout({ route, navigate }: Pick<Props,'route'|'navigate'>) {
  const planId = new URLSearchParams(route.split('?')[1] || '').get('plan') || '', product = products.find(item => item.id === planId);
  const [quote,setQuote] = useState<Quote|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),lock=useRef(false),idem=useRef(crypto.randomUUID());
  const quoteNow = async () => { if (!product || lock.current) return; lock.current=true; setBusy(true); setError(''); setQuote(null); try { const value=await api<Quote>('/membership/quotes','POST',{planId:product.id}); if(value.planId!==product.id||!value.id||value.currency!=='CNY'||value.autoRenew!==false||!Number.isFinite(value.total)||value.total<=0||Date.parse(value.expiresAt)<=Date.now()) throw new Error('服务端报价无效，请重新获取。'); setQuote(value); idem.current=crypto.randomUUID(); } catch(e){setError(messageOf(e));} finally{lock.current=false;setBusy(false);} };
  const submit = async () => { if (!quote || lock.current) return; if(Date.parse(quote.expiresAt)<=Date.now()){setError('报价已过期，请重新获取。');setQuote(null);return;} lock.current=true;setBusy(true);setError('');try{const result=await api<{orderId:string;checkoutUrl:string}>('/orders','POST',{quoteId:quote.id,idempotencyKey:idem.current});if(!result.orderId)throw new Error('订单返回信息不完整。');const target=new URL(result.checkoutUrl,location.origin);if(target.origin===location.origin&&target.pathname==='/payment-result')navigate('/payment-result?orderId='+enc(result.orderId));else if(target.protocol==='https:')window.location.assign(target.href);else throw new Error('支付链接无效。');}catch(e){setError(messageOf(e));}finally{lock.current=false;setBusy(false);} };
  if(!product)return <Empty title="没有找到这个商品" text="仅支持畅看月卡、季卡、永久会员和 220 永久积分。"><button className="secondary-button" onClick={()=>navigate('/membership')}>返回会员中心</button></Empty>;
  return <div className="form-stack latest-checkout"><h2>{product.title}</h2><div className="checkout-product"><strong>¥{money(product.price)}</strong><p>{product.kind==='credits'?`${product.points} 永久积分 · 永不过期`:product.durationDays?`${product.durationDays} 天 · 不自动续费`:'永久有效 · 无到期日'}</p>{festivalPhase()==='active'&&festivalBonus[product.id]&&<p className="festival-plan-bonus">支付成功加赠 {festivalBonus[product.id]} 天</p>}</div><p className="muted">订单、支付、权益和活动赠送均以服务端状态为准。返回支付页不代表支付成功。</p>{error&&<ErrorState error={error} retry={()=>void quoteNow()}/>} {!quote?<button className="primary-button" disabled={busy} onClick={()=>void quoteNow()}>{busy?'获取报价中…':'获取服务端报价'}</button>:<><div className="quote-card"><strong>{quote.currency} {quote.total.toFixed(2)}</strong><p>报价有效期至 {dateText(quote.expiresAt)}</p><p>单次购买 · 不自动续费</p></div><button className="primary-button" disabled={busy} onClick={()=>void submit()}>{busy?'正在提交…':'确认并前往支付'}</button><button className="secondary-button" disabled={busy} onClick={()=>void quoteNow()}>重新获取报价</button></>}<button className="text-button" onClick={()=>navigate('/membership-guide')}>会员与积分说明</button></div>;
}
export function CommercePage({route,navigate,onBack}:Props){
 const {session,login}=useApp(),path=route.split('?')[0],params=new URLSearchParams(route.split('?')[1]||''),id=path.startsWith('/me/orders/')?safeDecode(path.slice('/me/orders/'.length)):params.get('orderId')||'',isDetail=path.startsWith('/me/orders/'),endpoint=path==='/checkout'||path==='/payment-result'?null:id?'/orders/'+enc(id):'/orders',resource=useResource<RichOrder|RichOrder[]>(session?.subject?endpoint:null),title=path==='/checkout'?'确认订单':path==='/payment-result'?'支付结果':isDetail?'订单详情':'我的订单';
 return <PageShell title={title} onBack={onBack}>{!session?.subject?<Empty title="登录后查看订单"><button className="primary-button" onClick={login}>登录 / 注册</button></Empty>:path==='/checkout'?<Checkout key={route} route={route} navigate={navigate}/>:path==='/payment-result'?<section className="state-panel"><strong>正在核实订单</strong><p>支付结果以订单服务记录为准，请勿仅凭回跳页面判断支付成功。</p><button className="primary-button" onClick={()=>navigate(id?'/me/orders/'+enc(id):'/me/orders')}>查看订单状态</button></section>:resource.loading?<p role="status">正在查询订单…</p>:resource.error?<ErrorState error={resource.error} retry={resource.reload}/>:!resource.data||Array.isArray(resource.data)&&!resource.data.length?<Empty title="暂无订单信息" text="订单状态以服务端查询结果为准。"/>:(Array.isArray(resource.data)?resource.data:[resource.data]).map(order=><article className="notice-card order-card" key={order.id}><h3>{order.productName||products.find(p=>p.id===order.productId)?.title||'订单商品'}</h3><p>订单号：{order.id}</p><p>状态：{orderStatus[order.status]||'待确认'} · 权益：{order.entitlementStatus||'待确认'}</p><strong>{order.currency} {order.total.toFixed(2)}</strong><p>创建时间：{dateText(order.createdAt)}</p><p>有效期：{order.validity==='permanent'?'永久有效':order.durationDays?`${order.durationDays} 天`:'以订单权益记录为准'}</p>{!!order.extraViewingDays&&<p className="festival-plan-bonus">活动赠送 +{order.extraViewingDays} 天 · {order.status==='refunded'?'退款后应撤回':'支付成功后计入'}</p>}{order.refundStatus&&<p>退款状态：{order.refundStatus}</p>}{!id?<button onClick={()=>navigate('/me/orders/'+enc(order.id))}>查看详情</button>:<><button onClick={resource.reload}>刷新订单状态</button><button onClick={()=>navigate('/support/feedback?orderId='+enc(order.id))}>订单问题反馈</button></>}</article>)}</PageShell>;
}
