import { useState } from 'react';
import { api, dateText, enc, messageOf, safeDecode, type Ticket } from '../services/api';
import { useApp } from '../state/appState';
import { useResource } from '../hooks/useResource';
import { Empty, ErrorState, PageShell } from './Common';
export { MembershipPage } from './MembershipCenter';
export { CommercePage } from './CommerceScreens';
type Props = { route: string; navigate: (path: string) => void; onBack: () => void };
const topics = [
 {id:'account',title:'账号与登录',text:'使用账号和密码登录。注册账号为 4—20 位英文、数字或下划线，密码为 8—64 位；邮箱选填，未绑定邮箱时无法通过邮箱找回密码。'},
 {id:'playback',title:'播放与选集',text:'免费用户前 6 集可直接观看，具体以内容权限为准；付费单集基础价格为 5 永久积分。片源未上线、凭证过期或服务异常时可重新加载。'},
 {id:'membership',title:'会员与积分',text:'畅看月卡 ¥88/30天、季卡 ¥188/90天、永久会员 ¥388；均不自动续费。24小时体验每个符合资格账号限领一次。永久积分与会员积分分开记账，不能互换。'},
 {id:'orders',title:'订单与支付',text:'订单、支付、活动赠送和退款状态以服务端记录为准。月卡活动加赠7天、季卡加赠30天，仅支付成功后发放，退款时撤回。'},
 {id:'privacy',title:'隐私与记录',text:'设备普通记录与账号数据会明确区分。18+愿望榜仅在当前专区会话保存，不上传、不公开，刷新、退出专区或资格失效后清除。'},
];
export function SupportPage({route,navigate,onBack}:Props){
 const path=route.split('?')[0],feedback=path==='/support/feedback'||path==='/contact',tickets=path.startsWith('/support/tickets'),{session,login}=useApp(),resource=useResource<Ticket[]>(tickets&&session?.subject?'/support/tickets':null),[category,setCategory]=useState('播放问题'),[subject,setSubject]=useState(''),[description,setDescription]=useState(''),[contentId,setContentId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),ticketId=path.split('/')[3];
 return <PageShell title={feedback?'意见反馈':tickets?(ticketId?'反馈详情':'我的反馈'):'帮助中心'} onBack={onBack}>{feedback?<form className="form-stack" onSubmit={async e=>{e.preventDefault();if(!session?.subject){login();return;}setBusy(true);setError('');try{const params=new URLSearchParams(route.split('?')[1]||''),ticket=await api<Ticket>('/support/tickets','POST',{category,subject:subject.trim(),description:description.trim(),context:{source:'app',sourcePage:location.hash.slice(1),orderId:params.get('orderId')||'',contentId:contentId.trim()}});navigate('/support/tickets/'+enc(ticket.id));}catch(e){setError(messageOf(e));}finally{setBusy(false);}}}><p className="muted">反馈需要登录。请提供问题类型、来源页面及相关订单号或剧目ID。</p><label>问题类型<select value={category} onChange={e=>setCategory(e.target.value)}>{['播放问题','账号问题','会员订单','意见建议','隐私问题','版权问题'].map(value=><option key={value}>{value}</option>)}</select></label><label>标题<input minLength={2} maxLength={80} required value={subject} onChange={e=>setSubject(e.target.value)} placeholder="简要描述问题"/></label><label>问题描述<textarea minLength={10} maxLength={2000} required value={description} onChange={e=>setDescription(e.target.value)} placeholder="请描述操作步骤和遇到的问题（至少10字）"/></label><label>剧目ID（选填）<input value={contentId} onChange={e=>setContentId(e.target.value)} maxLength={80}/></label>{error&&<ErrorState error={error}/>}<button className="primary-button" disabled={busy}>{busy?'正在提交…':'提交反馈'}</button><button type="button" className="secondary-button" onClick={()=>navigate('/support/tickets')}>查看我的反馈</button></form>:tickets?!session?.subject?<Empty title="登录后查看反馈"><button className="primary-button" onClick={login}>登录 / 注册</button></Empty>:resource.loading?<p role="status">正在加载反馈…</p>:resource.error?<ErrorState error={resource.error} retry={resource.reload}/>:resource.data?.some(item=>!ticketId||item.id===safeDecode(ticketId))?resource.data.filter(item=>!ticketId||item.id===safeDecode(ticketId)).map(item=><article className="notice-card" key={item.id}><small>{item.status==='open'?'待处理':item.status==='processing'?'处理中':'已关闭'} · {dateText(item.createdAt)}</small><h3>{item.subject}</h3><p>{item.description}</p>{!ticketId&&<button onClick={()=>navigate('/support/tickets/'+enc(item.id))}>查看详情</button>}</article>):<Empty title={ticketId?'未找到这条反馈':'暂无反馈记录'}/>:<><div className="help-heading"><h2>有什么可以帮你？</h2><p>常见问题与使用指南</p></div>{topics.map(item=><details className="faq" key={item.id} open={path.endsWith('/'+item.id)||undefined}><summary>{item.title}</summary><p>{item.text}</p></details>)}<button className="primary-button" onClick={()=>navigate('/support/feedback')}>联系帮助 · 提交反馈</button><button className="secondary-button" onClick={()=>navigate('/support/tickets')}>我的反馈</button></>}</PageShell>;
}
const policyContent:Record<string,{title:string;sections:[string,string][]}>={
 terms:{title:'用户协议',sections:[['使用说明','请使用本人账号并妥善保管登录信息，不得侵犯他人权益或发布违法内容。'],['订单与权益','购买前请核对商品和金额。订单、支付、积分、会员及活动奖励以服务端结果为准。']]},
 privacy:{title:'隐私政策',sections:[['账户信息','登录与注册信息由账号服务处理，本应用不在本地保存密码。'],['设备记录','普通区访客观看和追剧记录可保存在当前设备；18+愿望榜只在当前专区会话保存，不上传、不公开。'],['管理信息','可在隐私设置中清空或逐条移除设备记录；账号云端数据以服务端确认结果为准。']]},
 'membership-guide':{title:'会员与积分说明',sections:[['畅看会员','畅看月卡¥88/30天、季卡¥188/90天、永久会员¥388；会员期内观看不扣永久积分，均不自动续费。'],['24小时体验','符合资格的免费用户可领取一次；限时会员领取后有效期增加1天；永久会员无需领取。'],['永久积分','永久有效，仅用于付费单集解锁。免费用户签到第1—6日每日1积分，第7日4积分；基础单集价格5积分。'],['会员积分','有效月卡、季卡会员签到每日获得1会员积分；20/50/100会员积分可兑换1/3/7天。两种积分不能互换，永久会员不再产生只能兑换时长的新会员积分。'],['内容权限','免费集范围以内容权限为准，已解锁剧集永久保留。18+内容仍需确认已满18周岁，会员身份不能绕过年龄确认。']]},
 copyright:{title:'版权说明',sections:[['尊重原创','作品权利归相关权利人所有，未经授权不得复制、传播或用于商业用途。'],['权利反馈','如有权利异议，请通过意见反馈提供作品信息和权属说明。']]},
 about:{title:'关于爱爱短剧',sections:[['爱爱短剧','好故事，一眼入戏。发现真人短剧与AI漫剧，管理追剧、评论、积分和会员权益。'],['联系我们','通过帮助与反馈提交建议，并在“我的反馈”查看处理状态。']]},
};
export function PolicyPage({route,onBack,navigate}:Props){const item=policyContent[route.slice(1)]||policyContent.about;return <PageShell title={item.title} onBack={onBack}><article className="policy-content">{item.sections.map(([heading,text])=><section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}<button className="secondary-button" onClick={()=>navigate('/support/feedback')}>帮助与反馈</button></article></PageShell>;}
