import { useState } from 'react';
import { Bookmark, Heart, MessageCircle, Play, Search, Share2 } from 'lucide-react';
import { dramas, type Drama, type Channel } from '../data/dramas';
import { useApp } from '../state/appState';
import { Comments } from './Comments';
import { Sheet } from './Sheets';
export function ReelsScreen({ paused: _paused, onSearch, onOpen }: { paused: boolean; onSearch: () => void; onOpen: (d: Drama) => void }) {
  const { records, toggle } = useApp(), [channel, setChannel] = useState<Channel>('推荐'), [comments, setComments] = useState<Drama | null>(null), [share, setShare] = useState('');
  const items = dramas.filter(d => channel === '推荐' || d.channel === channel).slice(0, 6);
  return <main className="reels-screen"><div className="reels-topbar"><div className="reels-tabs" role="tablist" aria-label="刷剧频道">{(['短剧', '漫剧', '推荐'] as Channel[]).map(c => <button key={c} role="tab" aria-selected={channel === c} onClick={() => setChannel(c)}>{c}</button>)}</div><button className="reels-search" aria-label="搜索短剧、漫剧" onClick={onSearch}><Search size={21}/></button></div><div className="reels-feed" key={channel}>{items.map(d => <section className="reel-slide" key={d.id} aria-label={d.title + '推荐'}><img className="reel-poster" src={d.cover} alt=""/><span className="reel-contrast"/><button className="reel-open-play" aria-label={'查看 ' + d.title} onClick={() => onOpen(d)}><Play size={36}/></button><div className="reel-actions"><button aria-label="喜欢" aria-pressed={records.liked.includes(d.id)} onClick={() => toggle('liked', d.id)}><Heart fill={records.liked.includes(d.id) ? 'currentColor' : 'none'}/><span>喜欢</span></button><button aria-label="评论" onClick={() => setComments(d)}><MessageCircle/><span>评论</span></button><button aria-label="收藏" aria-pressed={records.saved.includes(d.id)} onClick={() => toggle('saved', d.id)}><Bookmark fill={records.saved.includes(d.id) ? 'currentColor' : 'none'}/><span>收藏</span></button><button aria-label="分享" onClick={() => setShare(location.origin + location.pathname + '#/detail/' + encodeURIComponent(d.id))}><Share2/><span>分享</span></button></div><div className="reel-copy"><span className="reel-kicker">{d.genre} · {d.channel}</span><h1>{d.title}</h1><p>{d.tagline}</p><button className="full-drama" onClick={() => onOpen(d)}>查看短剧 · {d.status}<Play size={16}/></button></div></section>)}</div><Sheet open={!!comments} title="剧情讨论" onClose={() => setComments(null)}>{comments && <Comments contentId={comments.id} compact/>}</Sheet><Sheet open={!!share} title="分享短剧" onClose={() => setShare('')}><div className="form-stack"><label>复制链接分享<input readOnly value={share} onFocus={e => e.target.select()}/></label><button className="primary-button" onClick={async () => { try { await navigator.clipboard.writeText(share); setShare(''); } catch { /* selectable URL remains available */ } }}>复制链接</button></div></Sheet></main>;
}
