import { chromium, expect } from '@playwright/test';
import { mkdir,writeFile } from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-gpu','--renderer-process-limit=2']});
const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});
await context.addInitScript(()=>sessionStorage.setItem('aiai-app-intro-seen','1'));
const page=await context.newPage();const errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('docs/screenshots/polish',{recursive:true});
try {
 await page.goto('http://127.0.0.1:5173/#/me');
 await page.getByRole('button',{name:'登录',exact:true}).click();
 await page.getByRole('button',{name:'填入普通账号'}).click();
 await page.getByRole('dialog').getByRole('button',{name:'登录',exact:true}).click();
 await expect(page.locator('.profile-head')).toContainText('普通用户');
 await page.getByRole('button',{name:'退出账号',exact:true}).click();
 await expect(page.getByRole('button',{name:'登录',exact:true})).toBeVisible();
 await page.reload();await expect(page.getByRole('button',{name:'登录',exact:true})).toBeVisible();
 results.push('个人中心直接退出真实预览会话，刷新保持退出');
 await page.getByRole('button',{name:'登录',exact:true}).click();
 await page.getByRole('button',{name:'填入会员账号'}).click();
 await page.getByRole('dialog').getByRole('button',{name:'登录',exact:true}).click();
 await expect(page.locator('.profile-head')).toContainText('会员用户');
 await page.getByRole('button',{name:'退出账号',exact:true}).scrollIntoViewIfNeeded();
 await page.screenshot({path:'docs/screenshots/polish/logout-390.png'});
 for(const width of [360,390,430]){
  await page.setViewportSize({width,height:844});
  await page.goto('http://127.0.0.1:5173/#/following');
  const gaps=await page.evaluate(()=>{const tabs=document.querySelector('.library-tabs').getBoundingClientRect(),search=document.querySelector('.library-screen > .search-field').getBoundingClientRect(),next=document.querySelector('.library-screen > .search-field').nextElementSibling.getBoundingClientRect();return{top:search.top-tabs.bottom,bottom:next.top-search.bottom};});
  expect(gaps.top).toBeGreaterThanOrEqual(16);expect(gaps.bottom).toBeGreaterThanOrEqual(20);
  await page.screenshot({path:'docs/screenshots/polish/library-'+width+'.png'});
  await page.goto('http://127.0.0.1:5173/#/membership');
  await expect(page.locator('.membership-page')).not.toContainText('演示');
  await expect(page.locator('.membership-page')).not.toContainText('待正式');
  await page.getByRole('radio',{name:'月度会员',exact:true}).check();
  await page.getByRole('radio',{name:'悦享会员',exact:true}).check();
  await expect(page.locator('.membership-purchase')).toContainText('19.9');
  await page.screenshot({path:'docs/screenshots/polish/membership-'+width+'.png'});
  expect(await page.locator('.membership-page .subpage-content').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);
  await page.getByRole('radio',{name:'年度会员',exact:true}).check();
  await page.getByRole('radio',{name:'尊享会员',exact:true}).check();
  await expect(page.locator('.membership-purchase')).toContainText('328');
  await page.getByRole('radio',{name:'200 积分',exact:true}).check();
  await expect(page.locator('.membership-purchase')).toContainText('18');
  await page.getByRole('button',{name:'购买积分',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText('暂未开放购买');
  await expect(page.getByRole('dialog')).not.toContainText('演示');
  await page.getByRole('button',{name:'知道了',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0); await page.locator('.membership-page .subpage').evaluate(e=>e.scrollTop=e.scrollHeight);
  const clear=await page.evaluate(()=>document.querySelector('.membership-end').getBoundingClientRect().bottom<=document.querySelector('.membership-purchase').getBoundingClientRect().top);
  expect(clear).toBe(true);
  await page.screenshot({path:'docs/screenshots/polish/membership-bottom-'+width+'.png'});
  results.push(width+'px 间距、无横向溢出、月年套餐/积分金额、购买阻断、底部无遮挡');
 }
 await page.goto('http://127.0.0.1:5173/#/settings');await page.getByRole('button',{name:'退出登录',exact:true}).click();
 await expect(page.getByRole('button',{name:'登录账号',exact:true})).toBeVisible();
 await page.goto('http://127.0.0.1:5173/#/membership');
 await page.getByRole('radio',{name:'年度会员',exact:true}).check();await page.getByRole('radio',{name:'悦享会员',exact:true}).check();
 await page.getByRole('button',{name:'立即开通',exact:true}).click();
 await page.getByRole('button',{name:'填入普通账号'}).click();await page.getByRole('dialog').getByRole('button',{name:'登录',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'登录爱爱短剧'})).toHaveCount(0); await expect(page.getByRole('dialog',{name:'开通会员'})).toContainText('悦享会员年卡');
 await expect(page.getByRole('dialog')).toContainText('168');
 await page.getByRole('button',{name:'知道了',exact:true}).click();
 expect(await page.locator('.vip-emblem > svg').evaluate(e=>getComputedStyle(e).animationName)).toBe('none');
 results.push('设置退出仍可用；访客登录后保留年卡选择；减少动态效果生效');
 expect(errors).toHaveLength(0);
 await writeFile('docs/polish-verification.json',JSON.stringify({ok:true,results,errors},null,2));
 console.log(JSON.stringify({ok:true,results,errors},null,2));
} finally {await browser.close();}
